# 输出配置：隱藏 linter 名稱、穩定排序、逐行去重
output:
  print-issued-lines: true
  print-linter-name: false

# 运行参数：适度超时，避免下载依赖（只读模块模式）
run:
  timeout: 3m
  modules-download-mode: readonly

# 啟用的 linters（聚焦代碼風格與 import 整理）
linters:
  enable:
    - gofmt
    - goimports
    - gofumpt
    - gci

# 每個 linter 的細節設定
linters-settings:
  # gofmt 的 -s 簡化可能造成非預期重寫，預設關閉；需要更嚴格可設 true
  gofmt:
    simplify: false

  # gci 分組：標準庫、預設（第三方）、本地模組前綴
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/TonnyWong1052/aish)
