version: 2
project_name: aish

before:
  hooks:
    - go mod tidy

builds:
  - id: aish
    main: ./cmd/aish
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main._version={{.Version}}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: aish-archive
    builds:
      - aish
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

# nfpm packages - for deb/rpm
nfpms:
  - id: aish-nfpms
    builds:
      - aish
    formats:
      - deb
      - rpm
    vendor: "TonnyWong1052"
    homepage: "https://github.com/TonnyWong1052/aish"
    maintainer: "TomLeung <leungchushing1@gmail.com>"
    description: "AI shell helper."
    license: "MIT"
    bindir: /usr/local/bin
    scripts:
      postinstall: packaging/deb/postinstall.sh
      preremove: packaging/deb/preremove.sh
    contents:
      - src: packaging/deb/README.Debian
        dst: /usr/share/doc/aish/README.Debian
        file_info:
          mode: 0644
    recommends:
      - bash
      - zsh
      - fish

# Custom publishers for GitHub Pages APT repository
publishers:
  - name: "upload-to-apt-repo"
    ids:
      - aish-nfpms
    cmd: |
      # This will be handled by a separate GitHub Action
      # that uploads the .deb files to the apt repository
      echo "Packages built successfully"

changelog:
  use: git
  filters:
    exclude:
      - '^docs\('
      - '^chore\('
      - '^test\('

release:
  github:
    owner: TonnyWong1052
    name: aish
  draft: false
  prerelease: false

brews:
  - name: aish
    repository:
      owner: TonnyWong1052
      name: homebrew-aish
      branch: main
    folder: Formula
    commit_author:
      name: aish-bot
      email: releases@aish.local
    homepage: https://github.com/TonnyWong1052/aish
    description: AI shell helper
    license: MIT
    test: |
      assert_match "aish v{{.Version}}", shell_output("#{bin}/aish --version")
    dependencies:
      - name: go
        type: build
