version: 2
project_name: aish

before:
  hooks:
    - go mod tidy

builds:
  - id: aish
    main: ./cmd/aish
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main._version={{.Version}}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: aish-archive
    builds:
      - aish
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

changelog:
  use: git
  filters:
    exclude:
      - '^docs\('
      - '^chore\('
      - '^test\('

release:
  github:
    owner: TonnyWong1052
    name: aish
  draft: false
  prerelease: false

brews:
  - name: aish
    repository:
      owner: TonnyWong1052
      name: homebrew-aish
      branch: main
    folder: Formula
    commit_author:
      name: aish-bot
      email: releases@aish.local
    homepage: https://github.com/TonnyWong1052/aish
    description: AI shell helper
    license: MIT
    test: |
      assert_match "aish v{{.Version}}", shell_output("#{bin}/aish --version")
    dependencies:
      - name: go
        type: build
