name: release

on:
  push:
    tags:
      - 'v*'

# 並發控制：相同標籤僅保留最新一次執行
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          cache: true

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          # 使用具備 homebrew-aish 倉庫寫入權限的 PAT
          GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}
